name: CI Node.js

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repo
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar pruebas (opcional)
        run: echo "Aquí podrías poner npm test si tienes pruebas"

      - name: Listo
        run: echo "CI completado"

Agregar flujo CI
